### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by chanind** [jbloomAus/mats_sae_training#10]
Could this library be published on PyPI so it could be installed via `pip install` instead of needing to clone the git repo? It would make it much easier to install and use this library, as publishing on PyPI is usually the preferred way of sharing Python code.

The quickest path to this would be to do the following:
1. Move the library code into a folder with the same name as the library. If you want to call the library `mats_sae_training` so you can `pip install mats_sae_training`, then create a `mats_sae_training` folder and the `sae_training` and `sae_analysis` folders should be moved into that folder. Imports will then be `from mats_sae_training.sae_training import ...`.
2. Use a modern packing tool ([Poetry](https://python-poetry.org/), [PDM](https://pdm-project.org/latest/), or [Hatch](https://hatch.pypa.io/latest/) are all good choices)
3. Remove the `requirements.txt` and instead split dependencies between the main dependencies and dev dependencies in `pyproject.toml`.
4. Remove `.gitmodules` - it seems this isn't used anyway.

From there, you just need to run the `publish` command for the corresponding packing library you choose from above (e.g. `poetry publish` for poetry, or `pdm publish` for pdm, `hatch publish` for hatch), and you're basically done.

You can also set up automatic deployment with Github Actions using [Semantic release](https://semantic-release.gitbook.io/semantic-release/) so deployment happens automatically when committing to `main`, but that's not strictly required.

I can set up a PR with these changes if it's helpful.

**Comment by jbloomAus** [comment]
Hey @chanind, this sounds like a great idea. This is on my to do list (as well as sharing a roadmap for the code base / plans for what comes next). If you want to make a PR for it, this would be very useful :) I'm familiar with Poetry and so happy to use that. I've published / worked with python packages in the past and my current plan is to turn this code base into a "Transformerlens for SAEs".  

One thing worth noting is that I think this code needs better test coverage and docs before it'd be good for lots of people to be using it (but I won't say no to help if you'd like to contribute!) .

.gitmodules was supposed to be for geom-median as a submodule so it is getting used (I think?). It's not clear how critical it is to be using the geom median initialization, but if we do support it (and use code that isn't exactly what they have there) then we'll either need to  use a  fork of geom-median or submit a PR to it (at some point I wanted to geom median running on cuda but I can't recall if I actually got this working).

**Comment by chanind** [comment]
Makes sense! I can try to work on test coverage as well, that would probably help me understand how the SAE stuff is working anyway.

For the .gitmodules stuff, it looks like the repo currently has `sae_training/geom_median` as a normal direction committed to the repo, even though it's also listed in `.gitmodules`. I think currently the `geom_median` code is basicaly copy/pasted into this repo. Usually Github should link to the parent repo for submodules, and show up like: 
<img width="173" alt="Screenshot 2024-02-26 at 00 00 44" src="https://github.com/jbloomAus/mats_sae_training/assets/200725/b106fc99-9e6c-4d50-bae0-01678f879321">. I could be wrong though.

I guess as a first step I can try to make a PR moving to poetry and adding some tests, then when you're confident enough to publish on PyPI it should be quicker to do.

**Comment by chanind** [comment]
Looking at the repo pointed to by `.gitmodules`, https://github.com/jbloomAus/geom_median, there are no commits by you in that repo and it is exactly up to date with the repo it's forking, so I don't think it's possible that the modified `geom_median` code in this repo is coming from that source repo.
