### ISSUE TITLE
Type-checking is not enforced

### ISSUE THREAD

**Issue by chanind** [jbloomAus/mats_sae_training#15]
It looks like this library does make good use of type-hints, which is excellent, but these hints are not enforced and thus could be incorrect. Ideally, these types can be checked as part of the linting process using a type-checker. Some good choices are [MyPy](https://mypy.readthedocs.io/en/stable/) or [Pyright](https://github.com/microsoft/pyright). I can set up a PR implementing either of these if it's helpful.

**Comment by jbloomAus** [comment]
I'm open to this but have memories of this causing various issues in T-lens (using jax-typing). So I'm happy for a PR along those lines. I see Callum's code as the gold standard here (see typing in this [file](https://github.com/callummcdougall/sae_vis/blob/main/sae_vis/utils_fns.py) for example).

**Comment by jbloomAus** [comment]
@chanind closing this thanks to your PR :)

**Comment by chanind** [comment]
Ah the previous PR only addressed linting, not type checking. A PR is on the way to fix this too though...
