### ISSUE TITLE
SAEGroup config typing is incorrect

### ISSUE THREAD

**Issue by chanind** [jbloomAus/mats_sae_training#44]
Currently, SAEGroup is configured using the same config object as normal SAE objects, but the typings are incorrect since SAEGroups allow lists for each item in the config which turn into a SAE config for every permutation of values in lists in the config, while the config for SAEs do not. This means that configuring a SAEGroup currently will report typing errors.

I can envision two possible solutions:

### Solution 1: Create a dedicated `LanguageModelSAEGroupRunnerConfig` class
One solution is for SAEGroup and SparseAutencoder classes to each have their own dedicated config class to address this issue, likely with similar fields but with SAEGroup allowing lists of items. This means being less DRY (don't repeat yourself) in the config code, but I feel it's justified in this case for the simplicity and clarity it confers to the user. These two configs do correspond to separate concepts in the code, so it makes sense to have separate classes. We can add a test case to ensure these classes have the same keys so we don't accidentally add a key to one class but not the other.

### Solution 2: Create SAEGroup from a list of SAEConfigs, with helpers for generating permutations
We could have SAEGroup take in a list of SAEConfig objects directly, which would solve the typing issue  as there's no need then for a separate config for the SAEGroup, and would also give the user more direct control over what specific combinations of params they want to be running if they don't want every permutation. We could create some helper functions which can generate this list of SAEConfigs using combinations of values to enable the current behavior too. Something like:

```python
# Create based on combination of params on a base config, to match current behavior
base_config = LanguageModelSAEGroupRunnerConfig(...)
sae_group = SAEGroup.from_combinations(base_config, {
    'l1_coefficient': [1e-3, 1e-4, 1e-5],
    'd_sae': [1000, 5000],
})

# Create directly from a list of SAEConfigs
sae_configs = [
    LanguageModelSAEGroupRunnerConfig(...),
    LanguageModelSAEGroupRunnerConfig(...),
    LanguageModelSAEGroupRunnerConfig(...),
)
sae_group = SAEGroup(sae_configs)
```

I like solution 2 best, as it feels like it more directly addresses what we want a SAEGroup to be, which is simply a collection of SAEs with different params. It allows more flexibility than is possible currently since you can choose combinations of configs that don't need to include every possible permutation of options if you just have a few combinations you want to try out, while still allowing trying out all combinations of params if you'd like instead. It also avoids the DRY issues of having to create a separate, nearly identical config class, and the `SAEGroup.from_combinations()` method makes it really obvious what param combinations are being tried out since it lists them specifically, instead of needing to skim the whole config looking for items in lists.

**Comment by jbloomAus** [comment]
Let's go with option 2. This sounds reasonable.

**Comment by chanind** [comment]
I gave option 2 a try, but it ended up being a much larger change that I was anticipating. I'm also worried about potentially breaking loading of already pickled SAE models / configs. The option 2 diff is here: https://github.com/chanind/mats_sae_training/compare/main...chanind:mats_sae_training:fix-sae-group-typing.

This ends up being tricky for a few reasons:
- configs, rather than models/objects, are the core unit passed everywhere in the codebase, so modifying the config requires modifying everything
- existing SAEs are saved with `torch.save` which uses pickle, and any changes to any config classes (even changing the path or name of the config class) will break these old SAEs
- there are subtle differences between what's expected by all the various classes configs are passed to, e.g. ActivationsStore, SAE, SAEGroup, cache runner, and this means each of these end up needing a separate config class
- all these config classes get confusing since they're mostly identical, but we expect users to be hacking on the internals of the library and it's nice that there's basically just a single big config class to add params to for now
- even though SAEGroup in theory allows experimenting on any list of hyperparams, the majority of params cannot have multiple values in a SAEGroup (e.g. model name, batch size, etc...) or things will break. And we need a way to get at the common values for the whole group.

I'm thinking the simplest way for now might be to just add typing like `int | list[int]` for the few places in the config where we do allow users to specify a list of params for a SAE group, and add a bunch of validation checks to the SAE / SAEGroup classes where these list values are not valid. We'll have to add checks as well that things like `{layer}` are set in SAEGroup hook_point, but not in SAEs. This will mean a lot of explicit assertions throughout the code to assure Pyright that in a SAE, these values really aren't lists, but it's probably the least disruptive way forward for now. If in the future the requirements of a SAE vs SAEGroup vs ActivationsStore vs CacheRunner diverge in ways that are increasingly hard to reconcile, we may be forced to create new config classes, but we can cross that bridge when we come to it.
