### ISSUE TITLE
Colons in filepaths on Windows

### ISSUE THREAD

**Issue by jordansauce** [jbloomAus/mats_sae_training#6]
Windows cannot deal with colons in filepaths, so I can't clone the repo:

error: invalid path 'artifacts/sparse_autoencoder_gpt2-small_blocks.10.hook_resid_pre_6144:v2/1200001024_sparse_autoencoder_gpt2-small_blocks.10.hook_resid_pre_6144.pt'

**Comment by jbloomAus** [comment]
Hey,

Thanks for letting me know. I'm going to replace this shortly as that SAE
isn't needed/is old.

**Comment by jbloomAus** [comment]
fixed :)
